const axios = require("axios");
const prisma = require("../config/prisma");
const env = require("../config/env");
const { parseId, canAccessComplaint } = require("./common.service");

const getComplaint = async (user, complaintId) => {
  const complaint = await prisma.complaint.findUnique({
    where: { id: parseId(complaintId, "complaintId") },
    include: { category: true, department: true, jurisdiction: true },
  });

  if (!complaint) {
    const error = new Error("Complaint not found");
    error.statusCode = 404;
    throw error;
  }

  if (!canAccessComplaint(user, complaint)) {
    const error = new Error("You do not have access to this complaint");
    error.statusCode = 403;
    throw error;
  }

  return complaint;
};

const callAi = async (agentName, input) => {
  const response = await axios.post(`${env.aiServiceUrl}/analyze`, {
    agentName,
    ...input,
  });

  return response.data;
};

const runAgent = async (user, complaintId, agentName, handler) => {
  const complaint = await getComplaint(user, complaintId);
  const startedAt = Date.now();
  const agentRun = await prisma.aiAgentRun.create({
    data: {
      complaintId: complaint.id,
      agentName,
      inputJson: complaint,
      status: "PENDING",
    },
  });

  try {
    const output = await handler(complaint);
    await prisma.aiAgentRun.update({
      where: { id: agentRun.id },
      data: {
        outputJson: output,
        status: "SUCCESS",
        latencyMs: Date.now() - startedAt,
      },
    });
    return { complaint, output };
  } catch (error) {
    await prisma.aiAgentRun.update({
      where: { id: agentRun.id },
      data: {
        status: "FAILED",
        errorMessage: error.message,
        latencyMs: Date.now() - startedAt,
      },
    });
    throw error;
  }
};

const analyzeComplaint = async (user, complaintId) => {
  const { complaint, output } = await runAgent(user, complaintId, "complaint-analysis", (complaintData) =>
    callAi("complaint-analysis", { complaint: complaintData }),
  );

  const analysis = await prisma.aiAnalysis.create({
    data: {
      complaintId: complaint.id,
      summary: output.summary || output.message || null,
      translatedText: output.translatedText || null,
      detectedLanguage: output.detectedLanguage || complaint.language || null,
      categorySuggestion: output.categorySuggestion || null,
      prioritySuggestion: output.prioritySuggestion || null,
      departmentSuggestion: output.departmentSuggestion || null,
      locationSuggestion: output.locationSuggestion || null,
      confidenceScore: output.confidenceScore || null,
    },
  });

  return { analysis, output };
};

const routeComplaint = async (user, complaintId) => {
  const { complaint, output } = await runAgent(user, complaintId, "complaint-routing", (complaintData) =>
    callAi("complaint-routing", { complaint: complaintData }),
  );

  const routingDecision = await prisma.routingDecision.create({
    data: {
      complaintId: complaint.id,
      departmentId: output.departmentId || complaint.departmentId || null,
      officerId: output.officerId || null,
      reason: output.reason || output.message || null,
      confidenceScore: output.confidenceScore || null,
      isAiDecided: true,
    },
  });

  return { routingDecision, output };
};

const draftResponse = async (user, complaintId, payload) => {
  const { complaint, output } = await runAgent(user, complaintId, "response-draft", (complaintData) =>
    callAi("response-draft", { complaint: complaintData, instructions: payload.instructions }),
  );

  const draft = await prisma.resolutionDraft.create({
    data: {
      complaintId: complaint.id,
      officerId: user.id,
      draftText: output.draftText || output.message || "Draft response generated by AI service",
      generatedByAi: true,
    },
  });

  return { draft, output };
};

const listAnalyses = async (user, complaintId) => {
  const complaint = await getComplaint(user, complaintId);
  return prisma.aiAnalysis.findMany({ where: { complaintId: complaint.id }, orderBy: { createdAt: "desc" } });
};

const listAgentRuns = async (user, complaintId) => {
  const complaint = await getComplaint(user, complaintId);
  return prisma.aiAgentRun.findMany({ where: { complaintId: complaint.id }, orderBy: { createdAt: "desc" } });
};

module.exports = {
  analyzeComplaint,
  routeComplaint,
  draftResponse,
  listAnalyses,
  listAgentRuns,
};
